---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kserve-minio-secret
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAM8dXTisOLsncC6DOnHRxTB4P+f/FDKfaNrzP9lBo6n+SIzEq4/cztWa34K+mG06C7NsD1gZ+RAaGNKrTaUMdfDb2SeEU/1GJEzCWbZmLTlArkZxoZ3jd5jhn34bbv/EW1qcUTnYgIPHI0DBPEVlFkYwvntUYLla5ACQfmlvKj5o8DRnU8Fb9MfdFu8P9cJ6KLB4V3cQheNzH8JtegWLDNrYxMr4OVEcZCEYCwabkEnif+/ZfBak3BfEnGSrGqLGluzR4qakBWoEE1LZznFWhor76ZMFt7E/bw9eBnGwiW60AmjWbLqlkzPHOa3adEolD0apqThOVFBnbpbW6Jp7YQn6EUMyhzFf4350KzYWtYKWhb7BSqV0OtfDgvOpHV0XvX0rsEr3IVQa2NYOVufnjr9Q8QP8kLRLXhE8BlaCsKP9mCL2Dd+jM7tiyIrcD0kExMgv7NBI8fQBMi6O/m+BmD+qns0KsY8Nv4YQlKkVinzXA/dUUPzcTrrd2iAqu7c6J8X+aAlLtQBY5UW9iOLjwmEqs4gXRVclE0YQ6YJH/8TObWtFZCuZx0FI3Hbt+aG1bLrrsTNeC4dDFMmDIE6ziHntMUI4EWAxXCPLxjOBF6qC9eLKz0QmWkWqNyrt6JA4v9jkBhjSJoABhpJonFzV9zOSenXbncWMFPORMLKMJ0uyXLOBoo3RVOYRzp7m0NeBrbwIpwRAgApIPUdg==
    AWS_SECRET_ACCESS_KEY: AgC3+TEJO25otz3uY9wKSuf+GyTMntQZKMACfpkZH8NKAAQlV/saJhEp/t1WBm9/u/RJfnlAXO37ceQZS78dS2UiTrj5Vh4eeL4V9zDrFGBvRGFWzBi+9XXQDao6l4G2p+kNgQ45NJmEvrQWuVWxQdl2kfmWyz0zipFUyIwY3eVWSLfTF2HtOES1sJL5UT5kxR7rPwx862HLQuy2BBCytRWtGkUJ4NPJWVFuN0t3AsTIrfIr2WPj6IY/dUFNUM5FyTYhy0j5r1M6YHrfFSYRoyN2HYxWYQoEXo8z3ADwsI8tOmVOo93V4pqIUdsScGQa75tSJznLv150MV+XO9fYPsrsYFaARJy2iQPSC3+NtGqSRvV1e+gUicUniUitmD04dcev0LfTKApgP+m6ggmUrujdrhl5GR6pifXgc+7dRWK45Xcr+GjxY3cAMFV9UtYjK/AvWWkNH6GE7Qgru+Mqqc0eOXSiJgpdPyuNvVVziahIYJUlZTfVvJAHgtz7/LzSuKzyr6BaYcbnkPBRPIlLe91ztFuWxi6dlMMScYIFOZtRaYSUVM0pPSgRlWd15+xPl+gpnEXOSCJbt2kChp78YpAvr7f7l0X0UOKWMa8SnaVgmPVekt40DXxte89I3Ks9zgjCfOKgDlgOT/26c5Afox883lnMo0rOIhOQUp+5F5Seaan7Pmq7fk70m+7QRAYzKX5INwyCuyLB/heLu2sF/qMqI8+hK7Ln7VBOvIY=
  template:
    metadata:
      annotations:
        serving.kserve.io/s3-endpoint: minio.minio.svc.cluster.local:9000
        serving.kserve.io/s3-region: us-east-1
        serving.kserve.io/s3-usehttps: "0"
      name: kserve-minio-secret
      namespace: default
    type: Opaque
