apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: huggingface-classifier
  namespace: default
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: mlflow
      storageUri: s3://mlflow-artifacts/1/ceb3f060cf7a4312826ad347885407e8/artifacts/model
    canaryTrafficPercent: 10
    canary:
      modelFormat:
        name: mlflow
      storageUri: s3://mlflow-artifacts/1/ceb3f060cf7a4312826ad347885407e8/artifacts/model
