apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: huggingface-classifier
  namespace: default
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: mlflow
      storageUri: s3://mlflow-artifacts/1/d655616c239542ef83d4e3997009f863/artifacts/model
