---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: mlflow
spec:
  encryptedData:
    rootPassword: AgA0YgFPkJ32i5MUh+qBDE2mnEz5CZFLWr+bYNxB0oImNZANDjapjWsIFrvnKjrjjkfMrFoX7BuNoaiz6ZPQC15HtTWlbnPtzb2IqLpHH16tLhs0bxtF24GF5wO79xMbqIjFC+kotsBIgIYRMyj4oQtBz/W203QYHM1VI6FRrxLJCScIB2K53jyD/+2zITCF+EQgdjlOXys5gooDgsytq7JHfX0JnSt7FIpzkXwZ7GWCp+jiXY8ZS9nL3GjwhMqUWGbpiv+VWDZNmOVin4Z/8bHA6j35ANtavLCmdkbESQxDkoZQ6aYLg2lXPHjHJ0a08K0ROcl2UmfwgxbsYOfx4trTW7FcNKDOPRxu8R167Wa8WNac/MzpSyir8Sx9UrQEhwK4PDVZSVEjk+h7AFEwLIOd2q10apOW36pYO+AvdbO0pQx0Lci39HtzvNUWPwapXFuYcbizkfWxUgwPq+iaw1ZH9S8ebknr7gJ2v7knEHrUs88SKavLT4BC67nnbQBzfgE9Z0/K0QzY8m1DjPck/NJ0RNmj0hPprZLxqvOEk4Mwylf0qgJJyXj9ptIn5e1nlNjJT2ChwPl8CEwHeFCYCld+NNxpAmidOOkwm9uB+uK1HbgIybcAEfrOKZ+Twql5Tcbcov0VoCp4BKjKWbcNdKKUxOSUrlnqs3ZYFDWIXb6uofmV9yOmK+QMLiVHkGxBM0efE++ZjKQOzIK6OObUv8nkDx907yDG1JnY0SE=
    rootUser: AgASsNHr0OrPJF66uK9HeA6PeD8VBer+kuNw9EQMun/XYB5IqZPEJGtRCVDHHikDRJ+nkeU4tCKVbFGF/YiNFYHNzk+dpNBe5vjCVjuoS225zV8DBVFVNJuptTQmFcpR+niuiT0fVh+Gw+BBkVJQWV0shnpbBtTE/U0Aqkt3jnPed39WdlfluKCVJb6JPMRtqG6ZOUEJlgwzdGJtwCQdIuHz778hhEa8dhEBDMxdJYMrdSlS5BcTO6QI3ra9LoWb2BtDiioe4KV3ILzg1uvcB8gL7EaWBud490f6cVNAHTkA8TjLNrqCC/F46PfgXCoEC3csG/vBoZrY8kSuycwfNGM8AKOEa+jrdUa2VyVp6/yDAS394wLYxd3LFei1QoGgTx+ohdyxmFbV5yUI/A9Ezbg5A3TaaQBKbApeZNpWRtYUg2J42/NMaPukfbw3rG5hbzuM5VWL2NR1Qds6D3r0E62lieL4KdfzWSyPUOV3oYUdkFssPFnkkbK9j4RHCZgmYBWamernxHqILrS18676pWUeiDfiWHsP9XOMb/fYwmDaP6F4BazpdOI0JpUuLjziE/bN6SOC+StL1BQE3EADvCgbwmrV3kiq9s8Yu9u8oubzK3rKXycMZgySs164zfCGiLkanKzhZYHgadby1f0obxMFuTNJmcUjecuSxSF/WHpH6fA8Ucrfwfc1/Ki1rbnuVQctlWzbI8Q0DMa4/g==
  template:
    metadata:
      name: minio-creds
      namespace: mlflow
