---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgDThhNBkFHaj1eJoUvD/Kd51NnfBQKTnzSXa5pPkJzLkDIM+yLRxbq3JzMPSJ9pFCrQUbW30QC22JclkOpp3v1sQeI+4EBUO+LpTb7721S2CYmPzFOukl5rRiaOYAPig/BHbUpMJPR9706A6rwCEWsRFdcDXWB8QJUg41uBB6HqzYF1iDvkDhcXqm+iL4HSxREUOrmvcSHc+hFV46ayvZU1kQxzWsh+3tZA4WBe1I+jiP4SIlK/L+9M7q9d6DfwJvGDIVy154dZUeQDC+vTmM9n29egmf5lf+Xrl/74ndxI+FBJazkQXG3AKZw9Bscd4WG/S7YHN1jMqxpIso7gQ2pxxuVinYOZNeAU0tK26q8rWPXqHPpaC+89sow0RWD131D/Cx8iyoMm+IYMmufVwd3zXa1Tft7YCQFB2wI86DZGBcrf8MZ2czy2BwmgDE97Prb04+Ll1T1C1d4kL9GJYcfkQNO1B72dJYEqkIrB6BVYVQG8/8wmPMnYruv1NOF2INA5mg/9QosqAZEDrXq733HI0FXvTM+5UEHVXgSBucLdjDCTjp65wQpw2JcPr0awl4VDfx2No/RBJkU1WC6R30av72NmvUtD08d8Txt4prGfVh+h0NM7CcjXnAuwSbSJiowjN/AfQEqB3Oxx37dSMZekhjIQdFepMT5tEcSGcPvcXWMHoA6hj37Yv7XOOqB4iGWr5VHcOXKGfqVQJm0M5waaNWMHL4lYuTmyPbc=
    rootUser: AgCE0VG9ZSalcNBk6MzO9xW40HtyjNDyDXuxgOySyjVwbwgemb+NBxQSeuOy//FHvJPoJy9Ah7+3H9T2HxlWNQt7IDtr5nkni9L3yxSa6viMtWwMhldi7uVUOX/klhXa669FHmMIlfGj7N2Dvp7gVSG1bqKoceBituL6QKvXj2cIywax5WTc7I2FLyxPAfPyBuKTgEg1+9wNdCCzvndT1nUH0XJkC6pgShiXLdaxj3nxOjeNZ90jihYTgHzapdnRjtLGnOWVrtgJ6WcTtDL7LwO+/RQP5PtnaXfChcTR36b0wLABOzBSvwSK7ZLaAXpFoX7jsjI44cDSMijEp0cPB9WNxWKDG3WtHmvKNIUULWhRGKquh9GmA+7yR1hqByBHz9hoM3nKzgEGrsenpIIQEsgWC8OoTHE9dEkHfUQdDuM+vre4eGkOCI0K/jRpI1c2pXTgp7dGhRLEjvIO+jJe11BYRTVa7kOJoZPlYCcYpo1Gl5kPVi10wqN7MYt8m4UtXrZODkK0fSqJ+wLYDRWqGNET0K7jo6w0q/4g5wEPvVQpR1na7JzCJUKKT+bjv66Ib3CDY4bxvQQ3DH5w8HYJVt5BE2DiDByE8W1mctFAwgSAeMZUfJ4enDmobfRLhb1brq7NY7ZH1SEjGy9kiA9HacXSj1MMtYTNvfRbwaPvBExJyvfmWxnHkW8jbrrLBZnWVgqMz/HhELmcgWeNbQ==
  template:
    metadata:
      name: minio-creds
      namespace: minio
