apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-inference
  # This must be deployed into the namespace where ArgoCD is installed
  namespace: argocd 
spec:
  project: default
  source:
    # Your exact repository URL
    repoURL: 'https://github.com/KarthikSaladi047/MLOps-with-Kubeflow.git'
    # The branch where your infrastructure state lives
    targetRevision: ArgoCD
    # The specific folder containing your k8s-ui-backend.yaml
    path: Kserve
  destination:
    # Deploy to the cluster ArgoCD is currently running on
    server: 'https://kubernetes.default.svc'
    # The namespace where the FastAPI and Gradio pods will live
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true